version '3'
services:
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: raja123
    networks:
      - mongo
  
  mongo-express:
    image: mongo-express
    ports:
    - "8081:8081"
    environment:
    - ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: raja123
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: raja123
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - mongo

networks:
  mongo:
    driver: bridge