apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: boardgame
  labels:
    app: boardgame
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: raja1475/boardgame:1.0.0
          ports:
            - containerPort: 8080  # Assuming your app runs on port 8080
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  namespace: boardgame
spec:
  type: LoadBalancer  # This exposes the service externally
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Mapping external port 80 to internal container port 8080
